#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt interactivecomments

# Setup Prompt
autoload -Uz promptinit
promptinit
prompt oldpatricka
autoload osx

# Setup editor
export EDITOR=vim
export VISUAL=vim

# Setup Aliases
alias cd..="cd .."
alias chomp="PERL -pe 'chomp'"
alias git='nocorrect hub'
alias zreload='source ~/.zshrc'
alias history='history 0' # bash-style history
alias xmlpretty='xmllint --format -'

# Setup PATH
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:~/bin:~/src/enstratius/sandbox-meta/bin:/Users/patricka/.rbenv/versions/2.1.0/bin:/Users/patricka/.gem/ruby/2.0.0/bin:~/src/enstratius/sandbox-fe-dev/bin

# Setup Virtualenv
source /usr/local/bin/virtualenvwrapper.sh

# Setup rbenv
#eval "$(rbenv init -)"

source ~/.enstratius/env.sh

export JAVA_HOME="$(/usr/libexec/java_home -v 1.7.0)" # Force 1.7 to be our default.
#export JAVA_HOME="$(/usr/libexec/java_home -v 1.6.0)" # Force 1.6 to be our default.
export MAVEN_OPTS="-Xms256m -XX:MaxPermSize=1024m -Xmx2048m -Djava.awt.headless=true"
export EC2_PRIVATE_KEY="$(/bin/ls "$HOME"/.ec2/pk-*.pem | /usr/bin/head -1)"
export EC2_CERT="$(/bin/ls "$HOME"/.ec2/cert-*.pem | /usr/bin/head -1)"
export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.6.12.0/libexec"
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
export JAVA_HOME="$(jenv javahome)"
eval $(docker-machine env 2>/dev/null)
export GOPATH=$HOME
